micronaut:
  application:
    name: wattbiller-backend
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        signatures:
          jwks:
            rackfarmLogin:
              url: 'https://login.rack.farm/auth/realms/rackfarm/protocol/openid-connect/certs'
    endpoints:
      login:
        enabled: true
        oauth:
          enabled: true
      logout:
        enabled: true
        get-allowed: true
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
jpa:
  default:
    entity-scan:
      packages:
        - 'farm.rack.wattbiller.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
billing:
  period:
    timeunit: MONTH
    amount: 1

jackson:
  serialization-inclusion: NON_ABSENT
  serialization:
    writeDatesAsTimestamps: false

keycloak:
  admin:
    serverUrl: https://login.rack.farm/auth
    realm: rackfarm
    clientId: admin-cli
    clientSecret: ${wattbiller.keycloak.admin.clientSecret}
    username: rackfarm-realm-reader
    password: jTx2ECix732Zvh7Vw&sPn
  clientId: wattbiller
